package com.herosdk.common;

public enum PluginNode {
  AFTER_EXIT, AFTER_INIT, AFTER_LOGIN, AFTER_LOGOUT, AFTER_PAY, BEFORE_CHANNEL_INIT, BEFORE_CHANNEL_PAY, BEFORE_EXIT, BEFORE_INIT, BEFORE_LOGIN, BEFORE_LOGOUT, BEFORE_PAY, ON_ACTIVITY_RESULT, ON_APPLICATION_ATTACH, ON_APPLICATION_CREATE, ON_CREATE, ON_DESTROY, ON_NEW_INTENT, ON_PAUSE, ON_RESTART, ON_RESUME, ON_SPLASH_CREATE, ON_SPLASH_DESTROY, ON_START, ON_STOP, SUBMIT_ROLE_INFO;
  
  static {
    BEFORE_CHANNEL_INIT = new PluginNode("BEFORE_CHANNEL_INIT", 1);
    AFTER_INIT = new PluginNode("AFTER_INIT", 2);
    BEFORE_LOGIN = new PluginNode("BEFORE_LOGIN", 3);
    AFTER_LOGIN = new PluginNode("AFTER_LOGIN", 4);
    SUBMIT_ROLE_INFO = new PluginNode("SUBMIT_ROLE_INFO", 5);
    BEFORE_LOGOUT = new PluginNode("BEFORE_LOGOUT", 6);
    AFTER_LOGOUT = new PluginNode("AFTER_LOGOUT", 7);
    BEFORE_PAY = new PluginNode("BEFORE_PAY", 8);
    BEFORE_CHANNEL_PAY = new PluginNode("BEFORE_CHANNEL_PAY", 9);
    AFTER_PAY = new PluginNode("AFTER_PAY", 10);
    BEFORE_EXIT = new PluginNode("BEFORE_EXIT", 11);
    AFTER_EXIT = new PluginNode("AFTER_EXIT", 12);
    ON_CREATE = new PluginNode("ON_CREATE", 13);
    ON_START = new PluginNode("ON_START", 14);
    ON_RESTART = new PluginNode("ON_RESTART", 15);
    ON_PAUSE = new PluginNode("ON_PAUSE", 16);
    ON_RESUME = new PluginNode("ON_RESUME", 17);
    ON_STOP = new PluginNode("ON_STOP", 18);
    ON_NEW_INTENT = new PluginNode("ON_NEW_INTENT", 19);
    ON_ACTIVITY_RESULT = new PluginNode("ON_ACTIVITY_RESULT", 20);
    ON_DESTROY = new PluginNode("ON_DESTROY", 21);
    ON_SPLASH_CREATE = new PluginNode("ON_SPLASH_CREATE", 22);
    ON_SPLASH_DESTROY = new PluginNode("ON_SPLASH_DESTROY", 23);
    ON_APPLICATION_ATTACH = new PluginNode("ON_APPLICATION_ATTACH", 24);
    ON_APPLICATION_CREATE = new PluginNode("ON_APPLICATION_CREATE", 25);
    $VALUES = new PluginNode[] { 
        BEFORE_INIT, BEFORE_CHANNEL_INIT, AFTER_INIT, BEFORE_LOGIN, AFTER_LOGIN, SUBMIT_ROLE_INFO, BEFORE_LOGOUT, AFTER_LOGOUT, BEFORE_PAY, BEFORE_CHANNEL_PAY, 
        AFTER_PAY, BEFORE_EXIT, AFTER_EXIT, ON_CREATE, ON_START, ON_RESTART, ON_PAUSE, ON_RESUME, ON_STOP, ON_NEW_INTENT, 
        ON_ACTIVITY_RESULT, ON_DESTROY, ON_SPLASH_CREATE, ON_SPLASH_DESTROY, ON_APPLICATION_ATTACH, ON_APPLICATION_CREATE };
  }
}


/* Location:              D:\Code\Crack\dex-tools-2.1-20190905-lanchon\zspns-pcgw-P36417A-0429-dex2jar.jar!\com\herosdk\common\PluginNode.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       1.1.3
 */